---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# Passwords: you can run "docker run authelia/authelia:latest authelia hash-password 'password_change_me'"

# List of users
users:
  me:
    displayname: 'Me'
    password: '$argon2id$v=19$m=65536,t=1,p=8$Q01VZFh4S1I0Tkp6ZndUWg$LAM0uP5V7HXcCcuM0B4W2jN64N0fXEuUR8qz0cq1fzI'
    email: mail@example.com
    groups:
      - admins
      - dev
  guest:
    displayname: 'Guest'
    password: '$argon2id$v=19$m=65536,t=1,p=8$Q01VZFh4S1I0Tkp6ZndUWg$LAM0uP5V7HXcCcuM0B4W2jN64N0fXEuUR8qz0cq1fzI'
    email: guest@example.com
