# PMS - Personal Management System
#
# .env variables:
# DOMAIN = PMS subdomain + your domain
# MYSQL_DB = Database name
# MYSQL_PASS = Database password

version: '3.1'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - pms
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
    volumes:
      - ./data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /application
    volumes:
      - .:/application # Folder where you cloned PMS into (where this docker-compose is actually)
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - proxy
      - pms
    labels:
      - 'traefik.enable=true'
      # Router HTTP
      - 'traefik.http.routers.pms.entrypoints=http'
      - 'traefik.http.routers.pms.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.pms.middlewares=pms-https-redirect'
      # Router HTTPS
      - 'traefik.http.routers.pms-secure.entrypoints=https'
      - 'traefik.http.routers.pms-secure.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.pms-secure.tls=true'
      - 'traefik.http.routers.pms-secure.service=pms'
      # Authelia Middleware. Recommended as PMS dev didn't intend for this to be publicly available.
      - 'traefik.http.routers.pms-secure.middlewares=authelia@docker'
      # Middelwares
      - 'traefik.http.middlewares.pms-https-redirect.redirectscheme.scheme=https'
      # Services
      - 'traefik.http.services.pms.loadbalancer.server.scheme=http'
      - 'traefik.http.services.pms.loadbalancer.server.port=80'
      - 'traefik.docker.network=proxy'

  php-fpm:
    build: ./docker/php-fpm
    container_name: php-fpm
    working_dir: /application
    networks:
      - pms
    volumes:
      - .:/application

networks:
  pms:
    external: false
  proxy:
    external: true
