# Pihole
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
#
# .env variables:
# TZ -> Your timezone. Ex. "America/Argentina/Buenos_Aires"
# PH_DATA -> Data directory. Ex. "/folder/docker/pihole"
# PH_DNSMASQ Data directory. Ex. "/folder/docker/pihole/etc-dnsmasq.d/"
#
# Notes:
# - DNS:
#  v4: 1.1.1.1,9.9.9.9,1.0.0.1,149.112.112.112
#  v6: 2606:4700:4700::1111,2606:4700:4700::1001,2620:fe::fe,2620:fe::9
#
# - Troubleshooting
#  Make DNS work on the same system, or something like that.
#  - Steps (incomplete?, assuming sudo):
#
#    1. Install resolvconf: "apt install resolvconf"
#    2. Enable service: "systemctl enable resolvconf && systemctl enable resolvconf"
#    3. Edit /etc/resolvconf/resolv.conf.d/head and add "nameserver 1.1.1.1"
#    4. Restart: "systemctl restart resolvconf"
#    5. Check if changes were applied in /etc/resolv.conf
#    6. If changes dont apply, reboot.
#    7. Update config: "resolvconf -u"
#    8. Stop resolved: "systemctl disable systemd-resolved && systemctl stop systemd-resolved"

version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8101:80/tcp" # Your own port, different from 80
    environment:
      TZ: ${TZ}
      DNS1: '1.1.1.1'
      DNS2: '9.9.9.9'
      ServerIP: ${SERVER_IP}
      ServerIPv6: ${SERVER_IP6}
      # WEBPASSWORD: set a secure password here or it will be random (check logs for password)
    volumes:
      - ${PH_DATA}:/etc/pihole/
      - ${PH_DNSMASQ}:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
